export App from './App/App'
export Home from './Home/Home'
export Widgets from './Widgets/Widgets'
export About from './About/About'
export Survey from './Survey/Survey'
export NotFound from './NotFound/NotFound'
